name: comp-data
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.0.2
  - ipykernel
  - pip:
    - scipy==1.7.3
    - numpy==1.22.1
    - matplotlib==3.5.1
    - scikit-learn==1.0.2
    - seaborn==0.11.2